[package]
name = "sail-argentea-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
publish = false
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
grust-procedures = "=0.24.0"
sail-native-resource-ffi = { path = "../../../crates/sail-native-resource-ffi" }

[dev-dependencies]
indexmap = "2"
log = "0.4"
readonly = "0.2"

[profile.dev]
debug = 0
incremental = false

[profile.release]
debug = 0
