class NativeScalarUdf:
    def name(self) -> str: ...
    def aliases(self) -> list[str]: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class BoundSecondString:
    def __init__(self, session_id: str) -> None: ...
    @property
    def session_id(self) -> str: ...
    def scalar_udfs(self) -> list[NativeScalarUdf]: ...
